# Generated by Django 4.2.7 on 2023-11-04 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('date', models.DateField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request_data.child')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request_data.organization')),
            ],
        ),
    ]
