# Generated by Django 4.2.7 on 2023-11-04 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_data', '0002_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='assessement',
            new_name='assessment',
        ),
    ]
